import { Plan } from "./types";

export const fallbackPlans: Plan[] = [
  {
    id: "plan-romantic-sunset",
    title: "Sunset skyline dinner",
    hook: "Scenic golden hour, a polished dinner, and an easy romantic finish.",
    summary:
      "Start with a rooftop drink, shift into a standout dinner reservation, then slow the pace with dessert and city lights.",
    vibes: ["romantic", "foodie", "nightlife"],
    templateHint: "Rooftop drinks, then dinner",
    templateId: "rooftop_then_dinner",
    durationLabel: "3.5 hours",
    costBand: "$$$",
    weather: "Best on clear evenings",
    heroImageUrl:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80",
    mapsVerificationNeeded: true,
    constraintsConsidered: ["romantic atmosphere", "walkable finish", "evening pacing"],
    stops: [
      {
        id: "plan-romantic-sunset-1",
        kind: "venue",
        stopType: "rooftop_bar",
        name: "Aster Rooftop",
        description: "A first drink with skyline views and soft lighting.",
        whyItFits: "It delivers a cinematic start without forcing a long commitment.",
        mapsUrl: "https://maps.google.com",
      },
      {
        id: "plan-romantic-sunset-2",
        kind: "venue",
        stopType: "restaurant",
        name: "Lumi Dining",
        description: "A refined dinner stop with a menu that still feels fun.",
        whyItFits: "The pacing works well after drinks and keeps the night feeling elevated.",
        mapsUrl: "https://maps.google.com",
        phoneNumber: "+61290000001",
        address: "123 Harbour Street, Sydney NSW",
      },
      {
        id: "plan-romantic-sunset-3",
        kind: "venue",
        stopType: "dessert_shop",
        name: "Night Owl Gelato",
        description: "Dessert and a short wander instead of a long third venue.",
        whyItFits: "It keeps the last hour light and conversation-friendly.",
      },
    ],
    transportLegs: [
      { mode: "Walk", durationText: "4 min" },
      { mode: "Walk", durationText: "9 min" },
    ],
    bookingContext: {
      planId: "plan-romantic-sunset",
      restaurantName: "Lumi Dining",
      restaurantPhoneNumber: "+61290000001",
      restaurantAddress: "123 Harbour Street, Sydney NSW",
      partySize: 2,
    },
    source: "fallback",
  },
  {
    id: "plan-gallery-wine",
    title: "Gallery drift and wine bar",
    hook: "Quiet conversation, a thoughtful gallery stop, and a soft landing over wine.",
    summary:
      "A low-pressure afternoon built for browsing, reacting, and talking without needing a packed schedule.",
    vibes: ["romantic", "nerdy", "casual"],
    templateHint: "Gallery and wine bar",
    templateId: "gallery_and_wine_bar",
    durationLabel: "2.5 hours",
    costBand: "$$",
    weather: "Any weather",
    heroImageUrl:
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
    mapsVerificationNeeded: false,
    constraintsConsidered: ["indoor option", "conversation-first", "afternoon date"],
    stops: [
      {
        id: "plan-gallery-wine-1",
        kind: "venue",
        stopType: "art_gallery",
        name: "North Room Gallery",
        description: "A compact gallery with enough to react to without becoming a marathon.",
        whyItFits: "It gives the date a point of view and an easy shared activity.",
      },
      {
        id: "plan-gallery-wine-2",
        kind: "venue",
        stopType: "wine_bar",
        name: "Cellar Lane",
        description: "A moody wine bar with share plates and easy pacing.",
        whyItFits: "It extends the date naturally after the gallery without feeling formal.",
        phoneNumber: "+61290000002",
        address: "11 Oxford Street, Sydney NSW",
      },
    ],
    bookingContext: {
      planId: "plan-gallery-wine",
      restaurantName: "Cellar Lane",
      restaurantPhoneNumber: "+61290000002",
      restaurantAddress: "11 Oxford Street, Sydney NSW",
      partySize: 2,
    },
    source: "fallback",
  },
  {
    id: "plan-active-arcade",
    title: "Arcade sparks and street-food dinner",
    hook: "Playful energy first, then food and dessert while the vibe is still high.",
    summary:
      "A date that feels social and alive right away, with enough structure to avoid awkward downtime.",
    vibes: ["active", "casual", "nerdy"],
    templateHint: "Arcade night",
    templateId: "arcade_date",
    durationLabel: "3 hours",
    costBand: "$$",
    weather: "Any weather",
    heroImageUrl:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
    mapsVerificationNeeded: false,
    constraintsConsidered: ["interactive activity", "casual budget", "indoor fallback"],
    stops: [
      {
        id: "plan-active-arcade-1",
        kind: "venue",
        stopType: "arcade",
        name: "Electric Quarter",
        description: "A playful first stop with low-stakes competition.",
        whyItFits: "It gets both people participating immediately instead of just sitting.",
      },
      {
        id: "plan-active-arcade-2",
        kind: "venue",
        stopType: "casual_restaurant",
        name: "Laneway Dumpling House",
        description: "Comfort food with enough buzz to keep the momentum going.",
        whyItFits: "The transition from games to dinner feels effortless.",
        phoneNumber: "+61290000003",
        address: "98 George Street, Sydney NSW",
      },
      {
        id: "plan-active-arcade-3",
        kind: "venue",
        stopType: "dessert_shop",
        name: "Soft Serve Society",
        description: "A quick dessert stop on the way out.",
        whyItFits: "It rounds things off without dragging the night too long.",
      },
    ],
    bookingContext: {
      planId: "plan-active-arcade",
      restaurantName: "Laneway Dumpling House",
      restaurantPhoneNumber: "+61290000003",
      restaurantAddress: "98 George Street, Sydney NSW",
      partySize: 2,
    },
    source: "fallback",
  },
  {
    id: "plan-rainy-day",
    title: "Rainy-day museum reset",
    hook: "A weather-proof date with enough movement to stay engaging and enough comfort to feel easy.",
    summary:
      "Bookstore, coffee, museum, and dinner, all without betting the entire plan on clear skies.",
    vibes: ["casual", "nerdy", "romantic"],
    templateHint: "Rainy day indoors",
    templateId: "rainy_day_indoors",
    durationLabel: "4 hours",
    costBand: "$$",
    weather: "Great in rain",
    heroImageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    mapsVerificationNeeded: false,
    constraintsConsidered: ["weather backup", "indoors", "conversation-friendly"],
    stops: [
      {
        id: "plan-rainy-day-1",
        kind: "venue",
        stopType: "bookstore",
        name: "Paragraph Books",
        description: "A first stop built around browsing together.",
        whyItFits: "It creates natural conversation and lets the date ease in.",
      },
      {
        id: "plan-rainy-day-2",
        kind: "venue",
        stopType: "cafe",
        name: "Slow Brew",
        description: "A proper coffee stop before the museum.",
        whyItFits: "It gives the date a warm middle beat before the next activity.",
      },
      {
        id: "plan-rainy-day-3",
        kind: "venue",
        stopType: "museum",
        name: "Museum of Applied Stories",
        description: "An exhibit-rich museum that still feels approachable.",
        whyItFits: "It adds shared material to talk about before dinner.",
      },
      {
        id: "plan-rainy-day-4",
        kind: "venue",
        stopType: "restaurant",
        name: "Juniper Dining Room",
        description: "An easy dinner finish close to the museum cluster.",
        whyItFits: "It closes the loop with minimal transit and a more intimate mood.",
        phoneNumber: "+61290000004",
        address: "44 Castlereagh Street, Sydney NSW",
      },
    ],
    bookingContext: {
      planId: "plan-rainy-day",
      restaurantName: "Juniper Dining Room",
      restaurantPhoneNumber: "+61290000004",
      restaurantAddress: "44 Castlereagh Street, Sydney NSW",
      partySize: 2,
    },
    source: "fallback",
  },
  {
    id: "plan-beach-seafood",
    title: "Beach hour into seafood dinner",
    hook: "Fresh-air energy first, then a dinner stop that feels earned.",
    summary:
      "A breezy afternoon-to-evening transition built around beach time, reset time, and a standout seafood dinner.",
    vibes: ["outdoorsy", "romantic", "foodie"],
    templateHint: "Beach day into seafood dinner",
    templateId: "beach_day_into_seafood",
    durationLabel: "5 hours",
    costBand: "$$$",
    weather: "Best on warm clear days",
    heroImageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    mapsVerificationNeeded: true,
    constraintsConsidered: ["outdoorsy vibe", "scenic setting", "destination dinner"],
    stops: [
      {
        id: "plan-beach-seafood-1",
        kind: "venue",
        stopType: "beach",
        name: "Shelly Beach",
        description: "An easy coastal opener for a swim or shoreline walk.",
        whyItFits: "It gives the date sunlight and movement before dinner.",
      },
      {
        id: "plan-beach-seafood-2",
        kind: "venue",
        stopType: "seafood_restaurant",
        name: "Tide Table",
        description: "Seafood dinner with a polished but not stuffy feel.",
        whyItFits: "It keeps the coastal mood while giving the night a proper anchor.",
        phoneNumber: "+61290000005",
        address: "8 Marine Parade, Manly NSW",
      },
    ],
    bookingContext: {
      planId: "plan-beach-seafood",
      restaurantName: "Tide Table",
      restaurantPhoneNumber: "+61290000005",
      restaurantAddress: "8 Marine Parade, Manly NSW",
      partySize: 2,
    },
    source: "fallback",
  },
];
